all:
    hosts:
        localhost:
            ansible_connection: local
            ansible_python_interpreter: /usr/bin/python3
            ansible_user: "{{ user }}"
            ansible_password: "{{ password }}"
            ansible_become_pass: "{{ password }}"
            ansible_port: 22
    children:
        admin:
            hosts:
                ADMIN01:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ user }}"
                    ansible_password: "{{ password }}"
                    ansible_host: 192.168.1.200
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22
                ADMIN02:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ user }}"
                    ansible_password: "{{ password }}"
                    ansible_host: 192.168.25.200
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22
        server:
            hosts:
                FW:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ FW_user }}"
                    ansible_password: "{{ FW_password }}"
                    ansible_host: 192.168.1.254
                    ansible_port: 22
                AD01:
                    ansible_connection: ssh
                    ansible_shell_type: powershell
                    ansible_user: "{{ AD_user }}"
                    ansible_host: 192.168.3.253
                    ansible_password: "{{ AD_password }}"
                    ansible_port: 22
        linux_server:
            hosts:
                NAS01:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ usernas }}"
                    ansible_password: "{{ passwordnas }}"
                    ansible_host: 192.168.26.249
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22
                MONIT01:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ user }}"
                    ansible_password: "{{ password }}"
                    ansible_host: 192.168.3.252
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22
                MAILSERVER:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ user }}"
                    ansible_password: "{{ password }}"
                    ansible_host: 192.168.3.240
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22
                GLPI:
                    ansible_connection: ssh
                    ansible_python_interpreter: /usr/bin/python3
                    ansible_user: "{{ user }}"
                    ansible_password: "{{ password }}"
                    ansible_host: 192.168.3.251
                    ansible_become_pass: "{{ password }}"
                    ansible_port: 22

        client:
            hosts:
                WinWork01:
                    ansible_connection: ssh
                    ansible_shell_type: powershell
                    ansible_user: "{{ WIN_user }}"
                    ansible_host: 192.168.2.105
                    ansible_password: "{{ WIN_password }}"
                    ansible_port: 22
                    domain_ou: "OU=Atelier,DC=e3s,DC=intranet"
                    group:
                        - GpSecComputerAtelier
                Accueil:
                    ansible_connection: ssh
                    ansible_shell_type: powershell
                    ansible_user: "{{ WIN_user }}"
                    ansible_host: 192.168.25.23
                    ansible_password: "{{ WIN_password }}"
                    ansible_port: 22
                    domain_ou: "OU=Office,DC=e3s,DC=intranet"
                    group:
                        - GpSecComputerOffice
                Bureau1:
                    ansible_connection: ssh
                    ansible_shell_type: powershell
                    ansible_user: "{{ WIN_user }}"
                    ansible_host: 192.168.25.26
                    ansible_password: "{{ WIN_password }}"
                    ansible_port: 22
                    domain_ou: "OU=Office,DC=e3s,DC=intranet"
                    group:
                        - GpSecComputerOffice